title: WMDing 的博客
description: 极简风格 · 中文支持 · 记录建模与思考
baseurl: "" # GitHub Pages 上请留空
url: "https://wmding.github.io"

markdown: kramdown
theme: null
permalink: /:year/:month/:day/:title/
encoding: UTF-8

sass:
  style: compressed