# Site settings
title: Dingwm blog
email: wmding@qq.com
description: "记录一些技术类文章。"
baseurl: ""
url: "https://wmding.github.io"
#twitter_username: fzhz0207
github_username: wmding

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

plugins:
  - jekyll-archives

jekyll-archives:
  enabled:
    - tags
    - categories
  layout: archive
  permalinks:
    tag: '/tags/:name/'
    category: '/categories/:name/'